# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Haopeng Li
title: PhD Candidate
email: hoplee95@outlook.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  HopLee6
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: haopeng-li-b417a826b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-8175-5381

# Additional icon links
additional_links:
- title: Google Scholar
  icon: ai ai-google-scholar-square
  url: https://scholar.google.com/citations?user=YSg_iL4AAAAJ&hl=en

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  My name is Haopeng (Hop) Li, and I am a PhD candidate from The University of Melbourne, studying computer vision and video understanding, supervised by <a href="https://scholar.google.com.au/citations?user=6sWGL5wAAAAJ&hl=en" target="_blank">Tom Drummond</a>, <a href="https://mingming-gong.github.io/" target="_blank">Mingming Gong</a>, and <a href="https://scholar.google.com/citations?user=84qxdhsAAAAJ&hl=en" target="_blank">Qiuhong Ke</a>. My research interests include computer vision, video understanding, and multimodal learning. I have published several papers in recognized journals and conferences, such as TPAMI, WACV, and ICASSP.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Dec 2020 â€” Now
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **University of Melbourne, Melbourne, Australia**

          *PhD Â· Computer Science*
      - layout: left
        sub_title: Sep 2017 â€” May 2020
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Northwestern Polytechnical University, Xi'an, China**

          *MSc Â· Computer Science*
      - layout: left
        sub_title: Sep 2013 â€” Jun 2017
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Northwestern Polytechnical University, Xi'an, China**

          *BSc Â· Mathematics and Applied Mathematics*

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Aug 2023 â€” Dec 2023
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **University of Melbourne, Melbourne, Australia**

          *Tutor Â· Part-time Â· Computer Vision*
          
      - layout: left
        sub_title: Jun 2023 â€” Aug 2023
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Monash University, Melbourne, Australia**

          *Research Assistant Â· Part-time Â· Bridge Completion Cheating Detection*

      - layout: left
        sub_title: Jun 2022 â€” Aug 2022
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **University of Melbourne, Melbourne, Australia**

          *Research Assistant Â· Part-time Â· Sports Video Understanding*

      - layout: left
        sub_title: Jun 2020 â€” Dec 2020
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          ![image](profile.jpeg){: style="float: left"}
          
          **SenseTime Group Ltd, Beijing, China**

          *Research Intern Â· Full-time Â· Crowd Video Analysis*

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Jan 2023
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Progressive Video Summarization via Multimodal Self-supervised Learning** <a href="https://arxiv.org/pdf/2201.02494.pdf" target="_blank">[Paper]</a> <a href="https://github.com/HopLee6/SSPVS-PyTorch" target="_blank">[Code]</a> 

          *2023 IEEE/CVF Winter Conference on Applications of Computer Vision (WACV)*

          **Haopeng Li**, Qiuhong Ke, Mingming Gong, Tom Drummond

      - layout: left
        sub_title: Jan 2023
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Precondition and Effect Reasoning for Action Recognition** <a href="https://arxiv.org/pdf/2112.10057.pdf" target="_blank">[Paper]</a>

          *Computer Vision and Image Understanding (CVIU)*

          Hongsang Yoo, **Haopeng Li**, Qiuhong Ke, Liangchen Liu, Rui Zhang

      - layout: left
        sub_title: Oct 2022
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Doubly Deformable Aggregation of Covariance Matrices for Few-Shot Segmentation** <a href="https://arxiv.org/pdf/2208.00306.pdf" target="_blank">[Paper]</a> <a href="https://github.com/shadowxzt/dacm-few-shot.pytorch" target="_blank">[Code]</a> 

          *2022 European Conference on Computer Vision (ECCV)*

          Zhitong Xiong, **Haopeng Li**, Xiao Xiang Zhu


      - layout: left
        sub_title: Sep 2022
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Video Crowd Localization With Multifocus Gaussian Neighborhood Attention and a Large-Scale Benchmark** <a href="https://arxiv.org/pdf/2107.08645.pdf" target="_blank">[Paper]</a> <a href="https://github.com/HopLee6/VSCrowd-Dataset" target="_blank">[Dataset]</a>

          *IEEE Transactions on Image Processing (TIP)*

          **Haopeng Li**, Lingbo Liu, Kunlin Yang, Shinan Liu, Junyu Gao, Bin Zhao, Rui Zhang, Jun Hou


      - layout: left
        sub_title: Jun 2022
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Video Joint Modelling Based on Hierarchical Transformer for Co-summarization** <a href="https://arxiv.org/pdf/2112.13478.pdf" target="_blank">[Paper]</a> <a href="https://github.com/HopLee6/VJMHT-PyTorch" target="_blank">[Code]</a> 

          *IEEE Transactions on Pattern Analysis and Machine Intelligence (TPAMI)*

          **Haopeng Li**, Qiuhong Ke, Mingming Gong, Rui Zhang


      - layout: left
        sub_title: Dec 2021
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Action-ViT: Pedestrian Intent Prediction in Traffic Scenes** <a href="https://ieeexplore.ieee.org/abstract/document/9645208" target="_blank">[Paper]</a>

          *IEEE Signal Processing Letters (SPL)*

          Shengzhe Zhao, **Haopeng Li**, Qiuhong Ke, Liangchen Liu, Rui Zhang


      - layout: left
        sub_title: Apr 2021
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Reconstructive Sequence-Graph Network for Video Summarization** <a href="https://arxiv.org/pdf/2105.04066.pdf" target="_blank">[Paper]</a>

          *IEEE Transactions on Pattern Analysis and Machine Intelligence (TPAMI)*

          Bin Zhao, **Haopeng Li**, Xiaoqiang Lu, Xuelong Li

      - layout: left
        sub_title: May 2020
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Video Frame Interpolation via Residue Refinement** <a href="https://ieeexplore.ieee.org/abstract/document/9053987" target="_blank">[Paper]</a> <a href="https://github.com/HopLee6/RRIN-PyTorch" target="_blank">[Code]</a> 

          *2020 IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)*

          **Haopeng Li**, Yuan Yuan, Qi Wang

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: Be Proud of Yourself ðŸŒˆ

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
